### ISSUE TITLE
Adopt to latest changes in uninstallation

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/cli#111]
**Description**
The Kyma Installer will be improved for the uninstallation action, see https://github.com/kyma-project/kyma/issues/2942. Assure that "kyma uninstall" command will work with that changes

**Reasons**
Assure working software

**Comment by clebs** [comment]
Discussed the uninstall changes:
- Now all errors are all logged into the installer's `errorLog`
- Now the uninstallation is retried indefinitely until it succeeds (infinite loop if a component always fails).

Based on that information, the changes proposed for the CLI are:
- Introduce a default timeout for the uninstall command. Now a timeout is **always required**, otherwise the CLI could enter an infinite loop too.
- Adapt the error status messages printed by the CLI when a component fails to uninstall to reflect the new retry nature of the process.
- Error log will be printed at the end of the timeout as before, it will now usually contain all errors throughout the process, not only the last one.
