### ISSUE TITLE
Local k3d provisioning gives back "Port cannot be allocated: listen tcp :80: bind: permission denied"

### ISSUE THREAD

**Issue by VishnAndr** [kyma-project/cli#1123]
**Description**
When I try to use `kyma provision k3d`, it throws the following output.

  Checking if port flags are valid
  Checking if k3d registry of previous kyma installation exists
  Checking if k3d cluster of previous kyma installation exists
X Verifying k3d status
Error: Port cannot be allocated: listen tcp :80: bind: permission denied

It appears with kyma cli 2.0. In ubuntu.
I was able to create k3d cluster and deploy kyma 2.0 on the same machine in the past.
Then I deleted the cluster and this is what I get if I try to provision again.
There is no k3d cluster currently  (`k3d cluster list` is empty)

It works with `sudo kyma provision k3d` though. Which is not good neither convenient.

What could I check? What would be the reason? There is nothing else running on the machine (it is WSL2 on Windows with Docker Desktop installed on the host if it makes any difference)

**Expected result**

Be able to provision as many times as required.
**Actual result**
Getting the above error about port 80.

**Steps to reproduce**

**Troubleshooting**

**Comment by a-thaler** [comment]
Hi @VishnAndr, the K3D cluster is provisioned by default using port 80 for the loadbalancer. That is a reserved port in Linux and cannot be used without root privileges. The solution is to do a custom port mapping with the effect of that the ingress will be reachable under the custom port, that's why we made that an explicit thing.

```
kyma provision k3d -p 8080:80@loadbalancer
```

So in general that is not a bug but it looks like we need to improve the UX.
I suggest to add either a note to https://kyma-project.io/docs/kyma/latest/04-operation-guides/operations/02-install-kyma/#provision-and-install or even introduce tabs for the different operating systems.

Furthermore, it will be great to print a hint in the error message itself. We should check if it is possible to detect that error sceanio in the CLI

**Comment by VishnAndr** [comment]
Thanks @a-thaler for the explanation. Yes, some explanation in the documentation or a hint in cli output world be helpful.
When you say "the ingress will be reachable under the custom port" - what does it exactly mean?

**Comment by a-thaler** [comment]
We added an info message to the error output in the CLI.
K3D comes with a loadbalancer so that k8s services of type loadbalancer are supported, like the istio-ingressgateway; That can be resolved via http://localhost:80. That port can be customized to your port.

Having that, the services exposed via the api-gateway are reachable as well via that loadbalancer. As we are using subdomains for the exposure, the localhost approach will not work out. That's why the CLI by default sets a custom domain "local.kyma.dev" for the local setup which resolves to localhost. So your service exposed via the api-gateway can be reached via http://xxx.local.kyma.dev:80. In your case you would need to use the custom port instead of 80.

In case the resolution of the custom domain is not working for you, see https://kyma-project.io/docs/kyma/latest/04-operation-guides/troubleshooting/01-kyma-domain-unresolvable/#cause
