### ISSUE TITLE
Improve error handling for install command and provide more relevant data

### ISSUE THREAD

**Issue by tomekpapiernik** [kyma-project/cli#133]
**Description**

The error messages returned by the CLI are rather brief and don't give much insight into what actually went wrong, even when in `--verbose` mode. 

For example, this istio error: 
![image](https://user-images.githubusercontent.com/29116492/59593492-58ee2c00-90f2-11e9-9fa3-da8f045708df.png)

Using the [is-installed.sh](https://github.com/kyma-project/kyma/blob/master/installation/scripts/is-installed.sh) script of Kyma it was showing at some point that detail message: 
```
Step error:  Details: Helm install error: rpc error: code = Unknown desc = validation failed: [unable to recognize "": no matches for kind "DestinationRule" in version "networking.istio.io/v1alpha3", unable to recognize "": no matches for kind "DestinationRule" in version "networking.istio.io/v1alpha3", unable to recognize "": no matches for kind "attributemanifest" in version "config.istio.io/v1alpha2"
```

This error description is available to the user but requires a lot of digging.
And it says that the installation failed but indeed it re-tries and may succeed later.

**Reasons**

Help users identify the exact errors they get in the installation process which in turn allows them to find solutions in Troubleshooting docs and ask the right questions on Slack. 

**Goal**
- Show the errorLog attribute of the installation resource additionally to the static "kubectl logs" statement
- Improve the error status message, instead of error message "X Kyma installation failed" write something more tolerant like a warning "! Processing component istio failed, which may be OK. Will retry later..."

**Comment by a-thaler** [comment]
The verbose mode is printing any executed command and the related result, see also your screenshot. That helps a lot to debug CLI related problems.

Printing the logs of the installer is not related to the topic. It got removed by purpose. It was decided, as the installer logs may contain sensitive data. So instead the CLI prints how to retrieve the logs, so that it gets a conscious decision.
Exactly the same way the is-installed.sh script is doing it.

I think we should not print the logs just because we are in verbose mode. People will use it in automated processes, even in verbose mode, not thinking about the implications.
Instead we should improve the installer log approach by putting all sensitive things in secrets and not printing secrets.

**Comment by a-thaler** [comment]
Indeed I overlooked some logic in the is-installed.sh of kyma. There is a general timeout and a printing of current helm error log. I will extend the description to add that parts to the CLI as well.
