### ISSUE TITLE
create module: detect insecure registries

### ISSUE THREAD

**Issue by clebs** [kyma-project/cli#1367]
**Description**

The `--insecure` flag allows to push modules to insecure registries but this can also be automatically be detected if the `--registry` flag has a schema prefix.
To make the command more ergonomic, the following logic shall be implemented:
- Automatically detect the schema of a registry if present (http | https) and adjust the push call accordingly.
- If a registry has `http` schema and the `--insecure` flag is **not** explicitly set, prompt the user to confirm pushing to an insecure registry.

**Reasons**

Better ergonomics.

**Comment by Tomasz-Smelcerz-SAP** [comment]
@clebs In addition to the described checks, I've added a validation for conflicting values of the `--insecure` flag, when the flag value contradicts the registryURL (http/https)

**Comment by clebs** [comment]
Hi @Tomasz-Smelcerz-SAP,
that can actually never happen. We have 4 possibilities:

1. Flag = false (either explicitly or nor provided) and registry is secure (https) -> no warning needed
2. Flag = false (either explicitly or nor provided) and registry is insecure (http) -> warning needed
3. Flag = true and registry is  secure (https) -> no warning needed (will usually not happen)
4. Flag = true and registry is insecure (http) -> no warning needed (user explicitly allows insecure)

**Comment by Tomasz-Smelcerz-SAP** [comment]
Hi @clebs 
Thanks for your explanation, let me add mine :)
I have understood the code differently and that's why I wanted - for safety reasons - to prevent users of using "https://..." registry but explicitly (by mistake, copy/paste etc) setting the insecure flag to `true` - which they can.
This is the code snippet I've seen in the `pkg/module/oci/client.go`:
```
        scheme := "https"
        if c.insecure {
                scheme = "http"
        }
 ```
It looks like `c.insecure` is propagated from the value of the mentioned CLI flag.
So I thought we ARE changing the scheme of the  HTTP client by playing with this flag.
I will double-check.

**Comment by clebs** [comment]
That is how the current implementation works without detecting the registry schema.

As described in the issue though, the insecure flag is only there to explicitly avoid the warning and prompt when using an insecure registry (e.g. in automation).

**Comment by clebs** [comment]
Another thing I realised is, we need to also check when users provide a registry that has no schema in the URL (e.g. my-refistry.localhost:5000).

In that case I would suggest to do as the current implementation does:
- If insecure = false -> use `https`
- If insecure = true -> use `http`
