### ISSUE TITLE
`validate module` command: validate the internal module structure

### ISSUE THREAD

**Issue by tobiscr** [kyma-project/cli#1375]
**Description**

The CLI has to be extended to validate a Kyma module. The validation has to cover:

* Correct `ModuleTemplate` definition
* Module is correctly bundled / including all mandatory party
* Module can be correctly installed and is starting

**Reasons**

Give developers an option to analyse the technical correctness of a Kyma module.

**Attachments**

**Comment by janmedrek** [comment]
I am not sure this is feasible from a technical point of view. It would require the whole setup of Lifecycle Manager, Module Manager and a target cluster. This would mean a significant implementation effort from our side, the module teams should have a separate set of pipelines that will check their operators and ensure they work according to the requirements.

Since we plan on delivering a pipeline that will check all of the basic stuff (correctness, bundling, running) I will close this issue.
