### ISSUE TITLE
CLI warns about managed cluster while it is unmanaged

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/cli#1460]
**Description**
I deployed Kyma using the "kyma deploy" command using version 2.9 and I deployed it on a native Gardener cluster.

Afterwards I wanted to upgrade to the "main" branch and got warned by the CLI about that my cluster is a managed runtime which I should not upgrade on my own.

```bash
kyma deploy -s main
! CAUTION: You are trying to use Kyma CLI to change a managed Kyma runtime (SAP Kyma Runtime). This action may corrupt the Kyma runtime. Proceed at your own risk.
? Do you really want to proceed? Type [y/N]: y
X A Kyma installation was found, but compatibility between version '2.9.0' and 'main' is not guaranteed. This might cause errors! 
? Do you want to proceed with the upgrade to 'main'? Type [y/N]: y
/ Fetching Kyma sources (main)
```

Also pleeeease fix the spelling, it is named "SAP BTP, Kyma runtime", short "Kyma runtime"

**Expected result**
There is no warning that I want to modify a managed runtime as it is not a managed runtime.

**Actual result**
I got the warning.

The labels on my resources are like that:
```yaml
    reconciler.kyma-project.io/managed-by: reconciler
    reconciler.kyma-project.io/origin-version: 2.9.0
```

**Steps to reproduce**
```bash
kyma deploy
kyma deploy -s main
```

**Troubleshooting**

**Comment by Tomasz-Smelcerz-SAP** [comment]
Hi, could you provide the domain name of this cluster as defined in the KUBECONFIG? This name is used for SKR detection.
Thanks!

**Comment by a-thaler** [comment]
icke1.berlin.shoot.canary.k8s-hana.ondemand.com

**Comment by ebensom** [comment]
The problem is that for older runtimes, we also relied on the default Gardener domain. The other way would be just rely on kyma.ondemand.com but with that we would exclude old runtimes having the legacy, Gardener default domain.

A bullet-proof solution could also be that by using the provided kubeconfig, you check a K8S resource which for sure exist on a SKR abnd check whether it has the [reconciler.kyma-project.io/managed-by](http://reconciler.kyma-project.io/managed-by): reconciler annmotation or label. But of course the reconciler SKR being used has to be modified so that kyma deploy CLI command doesn't add the exact same label/annotation to the resources

**Comment by a-thaler** [comment]
I assumed that the check is exactly based on that annotation, don't see a reason to not rely on that only. It should not be about domains and specific landscapes but about if the instance was installed via a control plane or the CLI. If it is a control plane (even self-managed) then you should not interfere with it as it is "managed".. The warning could be kept even unspecific to the offering by just saying that this is a managed instance, you should not touch it

**Comment by Tomasz-Smelcerz-SAP** [comment]
We could also revert the reasoning: Perhaps it's easier to consider every instance as "managed", unless there's a label/annotation that indicates it was created using the CLI.
This has the advantage that instance "marking" and instance "checking" logic is in the same project: cli.
Otherwise we have to adjust (and keep-in-sync) the logic in three projects: cli, reconciler, lifecycle-manager (or some other central operator or it's config)

**Comment by Tomasz-Smelcerz-SAP** [comment]
@a-thaler Let's discuss the technical solution in a separate issue: https://github.com/kyma-project/cli/issues/1472

**Comment by janmedrek** [comment]
There is a ConfigMap in the SKRs that could be used, I believe it would be best to base on this until we have the new architecture running.
```
apiVersion: v1
data:
 is-managed-kyma-runtime: "true"
kind: ConfigMap
metadata:
 annotations:
  reconciler.kyma-project.io/managed-by-reconciler-disclaimer: |-
   DO NOT EDIT - This resource is managed by Kyma.
   Any modifications are discarded and the resource is reverted to the original state.
 creationTimestamp: "2022-11-21T14:27:03Z"
 labels:
  reconciler.kyma-project.io/managed-by: reconciler
  reconciler.kyma-project.io/origin-version: 2.9.1
 name: skr-configmap
 namespace: kyma-system
 resourceVersion: "1836549"
 uid: ccab3054-11c5-40d5-b453-e70e50908f8f
 ```
