### ISSUE TITLE
Detect a managed Kyma instance 

### ISSUE THREAD

**Issue by Tomasz-Smelcerz-SAP** [kyma-project/cli#1472]
**Description**

the https://github.com/kyma-project/cli/issues/1360 introduced a way to detect a managed cluster. The idea was to display a warning if the user tries to deploy/undeploy kyma in a managed environment using the CLI.

The proposed solution failed: https://github.com/kyma-project/cli/issues/1460

It looks like instead of detecting a _managed cluster_, the CLI should try to detect a _managed Kyma instance._
The reasons for that are:
- detecting a "cluster type" (managed/not managed) is quite hard.
- It may change with time as the underlying infrastructure changes - our solution will break silently.
- it may be even impossible in the future, with the support for "Bring Your Own Cluster" model.

What if we don't need to detect "cluster type" at all?
All we need is to check if there is a _managed kyma instance_ installed (or to-be-installed) on the cluster.
- If yes, we display a warning.
- If no, i.e: the cluster is empty or there is a _manually installed Kyma instance_ running, we can proceed.

How to detect manually installed Kyma instance?
I have two ideas here:

The first approach is to mark some global objects in the cluster with the help of the central components that mange Kyma instances running in the control-plane.
An example of that would be adding annotations to the *kyma-system* namespace by the reconciler and/or annotating *Kyma* objects managed by lifecycle manager.
The model requires adding the same logic to several distinct components: reconciler, lifecycle-manger, CLI
This increases the maintenance effort

The second approach is to assume that, by default, **all** instances are managed unless explictily marked as "manually manged" by the CLI. In that case it is the CLI that is directly on indirectly adding some "special" annotations during Kyma installation.
This model requires adding the logic only to one component: CLI.

**Comment by tobiscr** [comment]
The KCP reconciler should inject an annotation to the resources indicating that this resource is centrally managed by KCP and should not be touched by by a different tool.

When using server-side-apply, we could set a unique `manager` for the resources which indicates the it's a managed resources from KCP (https://kubernetes.io/docs/reference/using-api/server-side-apply/#managers).

**Comment by Tomasz-Smelcerz-SAP** [comment]
@clebs Could you give an example when this CLI-only approach may break? The only scenario that comes to my mind is a corner case, where user connects to a manged cluster just-in-time before KCP started Kyma installation. The CLI would then see an empty cluster, and would not show the warning. The user starts the Kyma installation using the CLI and 30 seconds later KCP starts managed Kyma installation on the same cluster.
This is the only scenario that I found, and I think it's really unlikely to happen.
Perhaps I am missing something... ?

**Comment by clebs** [comment]
What if I am a customer using OSS Kyma with very specific needs and have my own way of deploying by running the following?:
```bash
k3d cluster create --name kyma // or any other provider (gke, aks, etc...)

kustomize build ${URL_TO_LIFECYCLE_MANAGER} | kubectl apply
kustomize build ${URL_TO_MODULE_MANAGER} | kubectl apply
kustomize build ${URL_TO_MODULE_TEMPLATES} | kubectl apply

kubectl apply -f kymaCR.yaml
```

This "custom" installation would be marked as managed, but it actually is not.

Another very easy to happen case would be:
```bash
k3d cluster create --name kyma
kyma alpha deploy // lets assume the solution we go for is annotating the kyma-system namespace

kubectl annotate namespace kyma-system created-by=cli- // remove the annotation either intentionally or by mistake
```

Now an upgrade would trigger the warning although the cluster is not managed.

A third case that comes to mind that will for sure happen:
- I create a cluster with the CLI and deploy kyma with the CLI as well.
- I accidentally mess the cluster up and it is in a broken state (including the annotation)
- I want to redeploy to fix it.
- Warning confusing me even more shows up and since I broke the cluster I do not dare to confirm.

There are many cases were a user can very easily (intentionally or by accident) bypass whatever mark the CLI puts on a cluster when deploying kyma. Plus any custom setups and corner cases we don't even know.

The other approach guarantees that if a cluster is managed we can confidently warn the user knowing for sure that it is correct.

**Comment by Tomasz-Smelcerz-SAP** [comment]
@clebs "The other approach guarantees that if a cluster is managed we can confidently warn the user knowing for sure that it is correct." I disagree. The two examples you gave are related to the situation, where the user intentionally breaks the cluster, or the user is changing the annotations on objects. This as well can happen with a managed cluster, where users have root-like privleges AFAIK.

Your first example, a custom installation, is an advanced use case. This entire feature is NOT for advanced users. Advanced users doesn't need it, they will go through the warning confirming it anyway.

In my opinion this feature is just a "best-effort" (we can't 100% guarantee it's correctness, but we do our best) warning message for inexperienced users just to avoid stupid mistakes. Like forgetting K8s context switch or forgetting about the cluster they've connected last Friday.

Now one idea that may be useful:
How about changing our assumptions and just detect if the Kyma was installed using the CLI?
After all, if it was not installed with the CLI, how can the CLI be responsible for keeping the contracts - whatever they are?
If the CLI detects a Kyma that was NOT installed with CLI, then it may display the warning. This Kyma may be a custom installation or a managed Kyma - it doesn't matter. The CLI doesn't "recognize it" and cannot be held responsible for damages.

The warning could be:
```The existing Kyma instance looks like it was not installed by the Kyma CLI. The CLI can't guarantee that any contracts or requirements of the existing installation are supported. Are you sure you want to proceed?"

In that way we are covered against managed Kymas, custom installations and any other wild scenarios.
Of course, we're NOT covered from a scenario, when somebody plays with annotations, but for that there's no protection anyway.

**Comment by clebs** [comment]
@Tomasz-Smelcerz-SAP, I have to disagree on the assumptions made and on the proposed approach:
1. `User intentionally breaks the cluster`: I was never implying that (accidents can happen). Regardless, if a user purposely breaks their cluster, we must warn correctly anyway because we are responsible for those managed runtimes; it does not matter what the user does and what their intent is.
2. `This feature is not for advanced users`: Similar to the previous answer: user expertise is irrelevant, the AC is: show warning if (and only if) cluster is managed. Additionally, it will not be uncommon for people with no prior Kyma experience to try out things. Precisely in those cases is when this feature is most valuable.
3. `"best-effort"`: This feature should be reliable. Otherwise, we can close this issue since the current implementation is also a "best-effort". But as we have seen from the feedback from @a-thaler, we need to do better.
4. `changing our approach to just detect if Kyma was installed using the CLI`: As said in point 2, that is not the requirement: checking if a runtime is managed and checking if Kyma was installed with the CLI are two very different things, with very different implications and edge cases without any correlation. Additionally, it is likely that in the future managed runtimes might be deployed using the CLI.
If we have to choose to warn on every cluster that was not deployed with the CLI or was manipulated, or the current domain based approach, IMHO the current approach is more reliable.
5. `when somebody intentionally tampers with the annotations, there's no protection`: The solution proposed by @tobiscr would protect against it on managed runtimes (which are the only ones relevant for this feature).

**Comment by Tomasz-Smelcerz-SAP** [comment]
@clebs `The solution proposed by @tobiscr would protect against it on managed runtimes` If that's the case, then I am happy and we can go with that approach.
But is it? As far as I know, our users have admin-like permissions and are capable of messing up everything, if they want. Including the `manager` fields.

**Comment by a-thaler** [comment]
Shouldn't we differ current status and future.

With current approach, we either have the reconciler embedded into the CLI deploy command or it runs in a control plane. In both scenarios the reconciler will set proper annotations and in the control plane setup it even gets reconciled on manipulation. Leveraging the existing annotation will be fine in my opinion to decide on showing a warning or not. If you now check for the annotation value by checking "managed" or NOT "cli" is not really relevant I think.

In future we will use the new deploy command which will install the lifecycle management, but not the modules itself, right? So you would mainly use the deploy command to manage the control plane part which in a managed setup you anyway have no access to. Is there really a scenario/command where you change the module setup inside the data plane and you want to prevent that by showing a warning? So main question is, do we need to detect a managed data plane at all? For which kind of commands?

**Comment by Tomasz-Smelcerz-SAP** [comment]
@clebs `This means, if a user removes the annotation, in the reconciliation it will be restored.` This is similar to what I pointed out in [this comment](https://github.com/kyma-project/cli/issues/1472#issuecomment-1339280714) Initially. 
So I have a feeling we're running in circles....
Yes, it will be restored, but are there any hard guarantees for how long will that take?
Let's consider the following scenario: user somehow breaks things and it will take some number of seconds for the KCP to restore things.
Let's assume quite nice time of 30 seconds.
During first 10 seconds of this 30 user can launch the CLI, which will NOT detect a managed runtime, and proceed.
So in my opinion we have to give up and accept that we can't 100% reliably "know" if we're dealing with managed environment or not. Correct me if I am wrong!
If we accept that risk, which is tiny IMO, then we can go with `annotations` or even `field manager` solution as proposed by @tobiscr

**Comment by janmedrek** [comment]
I would go with the `annotating Kyma objects managed by lifecycle manager` approach, even in the OS - the dual-cluster setup will still work the same.

As for the old reconciler - I would skip it for now, it would require a major effort implementation-wise and the bug is not critical. And as @clebs mentioned, it brings a set of new problems to the table.

**Comment by nesmabadr** [comment]
Block by [#487](https://github.com/orgs/kyma-project/projects/30/views/13?pane=issue&itemId=23629194): the check (deploying using the config plane config) on the life cycle manager PR is failing since it's using the latest image tag not the PR tag.
