### ISSUE TITLE
Flags "--installer-dir" and "--installer-version" have a strange behavior

### ISSUE THREAD

**Issue by clebs** [kyma-project/cli#190]
The flags `--installer-dir` and `--installer-version` can be used to give a custom installer image to the CLI.
But the behavior is a bit strange:

1. Both flags have to be used together since `installer-dir` accounts for registry URL + image name part of the image (e.g. `eu.gcr.com/kyma-project/pr/kyma-installer`) and `installer-version` accounts for the image tag (e.g. `PR-4753-25f78d66`).
2. If `installer-version` starts with "PR", the registry URL is magically changed to `eu.gcr.io/kyma-project/pr`. This poses an issue for users who could also have a "PR" image in their company with their own docker registry. In that case, they will never be able to install their own PR images.

**Proposal:**
~~Replace both flags with a new flag called `installer-image` that takes a full image name with URL (if needed) and tag.~~

After an in depth analysis, the new proposal is:

Add a new `--source` flag that allows the user to tell the installation source for kyma. This flag shall unify `--installer-dir`, `--installer-version`, `--local` and `--release`. The options it accepts are the following:

1. Latest: will install the latest kyma on master.
   For example:
   ```bash
   kyma install --source latest
   ```
2. Local: will install kyma from the local sources.
   For example:
   ```bash
   kyma install --source local
   ```
3. Semantic release version: kyma will be installed from the given released version on github.
   For example:
   ```bash
   kyma install --source 1.3.0
   ```
4. Custom installer docker image: will use the given image to install Kyma.
   For example:
   ```bash
   kyma install --source eu.gcr.io/kyma-project/kyma-installer:1.3.0
   ```
   or for DockerHub:
   ```bash
   kyma install --source <my-docker-id>/kyma-installer:dev-1234
   ```

**Comment by suleymanakbas91** [comment]
Within CLI, these two variables are used to build the `kyma-installer` image using this [Dockerfile](https://github.com/kyma-project/kyma/blob/master/tools/kyma-installer/kyma.Dockerfile). As you can see on the Dockerfile, `INSTALLER_DIR` and `INSTALLER_VERSION` are only used to determine the `kyma-operator` image, which is the binary. They do not determine the version of the `kyma-installer` image with the resources. So, these two variables should either be called something else like `KYMA_OPERATOR_DIR` and `KYMA_OPERATOR_VERSION` or should be removed as the user doesn't need to know about `kyma-operator`. 

Instead, we should provide a flag called `installer-image` which should replace the `kyma-installer` image from the `installer.yaml`. If `local` flag is set, we can use the local `installer.yaml`; otherwise we can just use the `installer.yaml` from the release by replacing the image.
