### ISSUE TITLE
Document minimal system requirements for local Kyma deployments

### ISSUE THREAD

**Issue by tomekpapiernik** [kyma-project/cli#201]
**Description**

Consider documenting minimal system requirements, such as RAM and CPU requirements for local Kyma deployments (Minikube). Make sure that you describe these requirements in such a way that they don't get outdated the very next day after merging.

**Reasons**

Members of the community asked the question on numerous occasions wondering if they'll be able to run Kyma on their local machines or if they should turn to cluster deployments right away. 

**Attachments**

none

**Comment by bszwarc** [comment]
@suleymanakbas91 , @a-thaler 
I tried to set up Kyma with all the components enabled, but it won't work for me even with memory increased. 
I suggest writing something along these lines:

General
* The minimal requirements to set up Kyma LITE are 4 CPU and 8GB RAM (these are also the default ones)
* If you want to add more components we suggest using a cluster.  

Monitoring
* Due to the fact that monitoring requires high memory levels we recommend using a cluster to install Kyma with monitoring enabled. 

Because to be honest we don't know where the border is, and what exactly is needed to make it running. 
I'm trying now to run Kyma with memory increased and just monitoring enabled and we'll see how it goes. But I would just recommend using a cluster if somebody wants to have more than just Kyma Lite.

**Comment by a-thaler** [comment]
Sounds fair. Have you tried it with 12GB already? I know it is a lot...

**Comment by bszwarc** [comment]
This one is handled as part of #6884 
Also - yes, tried with 10GB and it worked fine, but I don't know we should place specific numbers there.
