### ISSUE TITLE
Improve documentation for `-c` flag on `test run` command

### ISSUE THREAD

**Issue by k15r** [kyma-project/cli#261]
**Description**

With the current help message it is hard to figure out how the `-c` flag on `test run` works. Please update the help with a little example that shows that currently you have to add --max-retries 0 to the command, otherwise it will just run once

**Comment by bszwarc** [comment]
Will be done as part of #251.

**Comment by bszwarc** [comment]
Currently, the doc says:  `Number of execution rounds for each test in the suite. You cannot configure this value in parallel with max-retries. (default 1)`. 
This is not exactly true, because you need to set `max-retries` to `0` so that it works properly and runs the tests the specified number of times. If you just put `kyma test run  <test def> -c <int> ` it will use the default number of `max-retries` (which is `1`). This causes the whole test suite to be executed just once, regardless of the number provided for the `-c` flag. 
For the `-c` flag to work properly, you must explicitly set `max-retries` to `0` when using the command. 

I can write this in the documentation, but should it really work this way? Maybe `max-retries` should default to `0` or there is a different solution to this situation? 
@clebs, @a-thaler, what do you think?
