### ISSUE TITLE
Radomly instalation of kyma fails.

### ISSUE THREAD

**Issue by dbadura** [kyma-project/cli#339]
**Description**
Hello, very often instalation kyma on minikube fails. I don't know why
I am using:
minikube - 1.6.1
kubectl - 1.17 (tried with 1.12)
kyma-cli - 1.8.0

**Expected result**

Kyma is up and running 

**Actual result**
Kyma installation fails with weird log:
Here is a log:
https://bin.privacytools.io/?aaa8d552c7f64938#WI+tvwcdzMWTgda1rcN/QwLQk7LzwhNmRvAbE7J39bQ=

**Steps to reproduce**
run in cmd:
```bash
kyma provision minikube
kyma install
```

**Troubleshooting**

**Comment by clebs** [comment]
Hi @dbadura,

thanks for the report.

The first thing I see is that you are using minikube `1.6.1` instead of the supported `1.3.1`, so my first suggestion would be to install that minikube version.

Regarding the error itself, this happens when kubectl is not able to connect to the cluster, the error message is unfortunately not very good.

Please check the following: 
- Your current context is pointing to the right cluster.
- You do not have any networking software active that could break your connection to minikube (such as VPN or corporate local network firewalls).

**Comment by dbadura** [comment]
Hi,

I clean up the whole config and downgraded minikube to `1.3.1` and now it's seems thats it works.
I think that the minikube is too new for kyma.
