### ISSUE TITLE
How to version external dependencies?

### ISSUE THREAD

**Issue by sjanota** [kyma-project/cli#35]
## Problem

Right now we have dependency on following external tools:
* kyma CRDs
* kubernetes
* helm
* minikube

and soon to come:
* gcloud
* aks
* octopus 

There is growing problem we'll have to face one day, which is how do we approach versioning of those dependencies. Two basic approaches are:
1. Embed the tool within kyma-cli, like we did with helm.
    Pros:
    * Client is not required to have helm.
    * We use API instead of parsing strings which is usually better.
    Cons:
    * Not every tool can do that, for instance minikube.
    * Binary size grows to infinity.
    * Tool version is bound to source code, so use of #25 is limited.
2. Use binaries
    Pros:
    * Binary is lighter.
    * Client needs only to install new version of required tools in case of upgrade, CLI is cross-compatible with different versions of Kyma.
    Cons:
    * Client is required to install all the tools in addition to installing kyma-cli.
    * We need to deal with strings, not good.

None of those two solves problem of breaking changes in CRDs.

## Proposal
I suggest a mixed approach. There are three tools that are needed to provide core functionality: kyma CRDs, kubernetes and helm, which will soon get replaced by octopus. 

1. Kubernetes is the only binary dependency we have. According to [client-go](https://github.com/kubernetes/client-go#compatibility-your-code---client-go) it should be backwards compatible so we could bind kyma-cli to version supported by latest Kyma release. This should give us the ability to work with past Kyma releases as well as with future ones. Same applies to helm until we get rid of it.

2. We have also dependency on Kyma and Octopus CRDs. They are versioned together so we may treat them as one. The only option I see is to have a switch in the code which chooses appropriate "driver" depending on dependency version.
    * Octopus version will be bound to Kyma release, so we may treat them as one dependency.
    * We can build two separate drivers, for Kyma and for Octopus

All the other dependencies will be served as binaries. If you want to run Kyma on minikube, you have to have minikube installed in appropriate version. If you want to install on GKE, you have to have gcloud installed, and so on. Alternatively GKE module may use go client for GKE, but I wouldn't force anything here.

**Comment by a-thaler** [comment]
We will have dependencies for the main CLI functionality like kubectl and octopus and we have dependencies which gets activated optional dependent on the choosen cloud provider (minikube, gcloud, ...)

I suggest to keep all optional things as binary, so the size will not grow dependent on number of supported cloud providers. Furthermore we do not need to release just because a cloud provider fixed a security problem.
The main dependencies like kubectl and octopus will improve the maintenance/testability/development a lot and the versioning is in relation to kyma itself (kyma defined kubernetes and octopus version). So this dependencies should be as libraries.
