### ISSUE TITLE
Installing kyma using kyma-cli fails when helm 3.X is present.

### ISSUE THREAD

**Issue by rakesh-garimella** [kyma-project/cli#353]
**Description**

If a user is installing kyma using kyma-cli and has helm 3.x present then installation fails. Kyma-cli should try to check if helm 3.X is present on the system and should not start the installation giving the info message.

**Comment by a-thaler** [comment]
The CLI will configure your Helm installation at the "kyma install" command with the required certificates retrieved from the installed kyma cluster. That's all, there is no real dependency in order to install kyma using the CLI. If helm is not installed it just passes the point and continues. Same should happen with a Helm 3 installation, just ignore it and continue.
