### ISSUE TITLE
Mismatch of node number for GKE provisioning

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/cli#406]
**Description**

I created a GKE cluster using
```
kyma provision gcp --name=XXX --project=XXX --location=europe-west2 --credentials=XXX
```

I assume that the default number of nodes (3) gets used. Indeed it turned out that the default number gets used per zone, so at the end the cluster had 9 nodes.

It looks like the problem does not exist with CLI 1.10

**Expected result**
The cluster will have a maximum of 3 nodes to not be surprised from cost perspective.
I would love if also autoscaling is enabled ba default

Please check how the settings are applied for a gardner GCP cluster to have same behaviour.

**Actual result**
The cluster has 9 nodes (3 on each zone)

**Steps to reproduce**

**Troubleshooting**

**Comment by clebs** [comment]
Just investigated the cause of this issue and it is happening in master and previous versions.

It is an issue with the location flag and the fact that it can either be a region or a zone. This happens depending on the location:
- If location is a region (e.g. `europe-west-3`) you get n nodes per zone, so 3n (regions a,b,c).
- If location is a zone (e.g. `europe-west3-a`) you get only n nodes.

Therefore, we need to change how we set the nodes on GKE so that it is total nodes and not per region.
