### ISSUE TITLE
kyma-cli is not `go get`able and build does not work without -o flag

### ISSUE THREAD

**Issue by k15r** [kyma-project/cli#443]
**Description**

For smaller go programs installation is usually quite easy. 
`go get <import-path of command>`

For kyma cli this would mean: 
`go get github.com/kyma-project/cli/cmd/kyma`

>**NOTE:** according to https://github.com/golang-standards/project-layout/blob/master/cmd/README.md there should be a subfolder in cmd for every binary you want to build. Sticking to this would fix both issues.

unfortunately this does not work, as there is no main package at this location in the repository.

Another issue with the location of main.go (and therefor the main-package) is, that
`go build` does not work as is should.
Usually `go build <importpath of command>` would build a binary with the name of the binary inferred from the folder
In kyma-cli's case this does not work, as the folder is called `cmd` , and therefor the binary would be called `cmd` 

**Expected result**

`go get` and `go build` work

**Actual result**

`go get` does not work
`go build` requires -o parameter 

**Steps to reproduce**

**Troubleshooting**

possible solutions:

1. move main.go to root-level: this would allow `go get` and `go build` to work with the downside of the resulting binary being called cli
2. move main.go to cmd/kyma/main.go: this would fix both issues. currently there is a package at this location.

**Comment by clebs** [comment]
Hi @k15r,
the CLI is not go gettable so that `go get` and `go install` do not work on purpose.
This application needs some flags to be set at compile time and we are doing some compiler adjustments to reduce the binary size significantly.

In the current PR linked to this issue, when building the binary with `go build` or `go install`:
- Binary goes up to 80MB in size as opposed to 65MB with `make build`.
- The `Version` and `KymaVersion` flags are not set at compile time, therefore the `kyma version` and `kyma install` commands will not work.
- CGO is enabled per default, which means the binary is v.

The only go get scenario that does work is when downloading the repo to import some of its packages, but we want to avoid people using the go tooling to compile and run the application.

**Comment by k15r** [comment]
Hi @clebs,
Thanks for the quick reply.

i'm not saying that the current way of building has no benefits, but:
- with `kyma-cli` built from master i think it is fine to show Version N/A
- default to `latest` in the kyma install step
- Filesize: probably also more of a concern for a released version.
as this is mainly for developers.

For the production use case it still makes sense to release never versions

all those issues have been addressed by adapting the makefile as well.
- linkerflags are fixed
- make install fixed (did not work before as it installed a tool called `cmd`, not properly installs a tool called `kyma`)

The PR is just meant as a PoC

**Comment by clebs** [comment]
Well, those assumptions might not be correct and we need to discuss if they are acceptable.

**Comment by clebs** [comment]
After discussing the pros and cons of this change, we have decided that it is better to keep the structure as it is, even if it means that it is not installable via `go get`.

Should there be a better option to make this go-gettable in the fiuture, please reopen this issue.
