### ISSUE TITLE
Cannot provision gke cluster when working directory is /tmp

### ISSUE THREAD

**Issue by nachtmaar** [kyma-project/cli#540]
**Expected result**
A gke cluster cannot be provisioning using kyma cli when working directory is /tmp.

**Expected result**

Provisioning of gcp clusters works from any working directory.

**Actual result**

```shell
$ kyma version
Kyma CLI version: 1.14.0-rc4

$ kyma-provision-gcp nachtmaar-stackdriver-9
X Provisioning GKE cluster
Error: All attempts fail:
#1: unable to provision gcp cluster:
Error: Failed to read module directory

Module directory
../Users/xxx/.kyma/clusters/gcp/sap-sap-kyma-tunas-dev/nachtmaar-stackdriver-9
does not exist or cannot be read.

#2: unable to provision gcp cluster: There are some problems with the configuration, described below.

The Terraform configuration must be valid before initialization so that
Terraform can determine which modules and providers need to be installed.
Error: Failed to read module directory

Module directory
../Users/xxx/.kyma/clusters/gcp/sap-sap-kyma-tunas-dev/nachtmaar-stackdriver-9
does not exist or cannot be read.

#3: unable to provision gcp cluster: There are some problems with the configuration, described below.

The Terraform configuration must be valid before initialization so that
Terraform can determine which modules and providers need to be installed.
Error: Failed to read module directory

Module directory
../Users/xxx/.kyma/clusters/gcp/sap-sap-kyma-tunas-dev/nachtmaar-stackdriver-9
does not exist or cannot be read.

```
**Steps to reproduce**

```shell
kyma-provision-gcp () {
        if [[ $# -lt 1 ]]
        then
                echo "Usage: kyma-provision-gcp <cluster-name>"
                echo "Provisions a k8s cluster on gke"
                return
        fi
        KYMA_GCP_K8S_SERVICE_ACCOUNT=${KYMA_GCP_K8S_SERVICE_ACCOUNT:-"$HOME/.tunas/secrets/gcp/k8s-service-account.json"}
        if [[ ! -s ${KYMA_GCP_K8S_SERVICE_ACCOUNT} ]]
        then
                echo "error: gcp service accont does not exist or is empty: $KYMA_GCP_K8S_SERVICE_ACCOUNT"
                return
        fi
        local name="${1}"
        local k8s_version="${2:-1.16}"
        kyma provision gke -p sap-sap-kyma-tunas-dev -n "${name}" -c "${KYMA_GCP_K8S_SERVICE_ACCOUNT}" -l europe-west1-b --nodes 3 -k "${k8s_version}"
}
cd /tmp/
kyma-provision-gcp <cluster-name>
```

**Comment by a-thaler** [comment]
Another client reported similar behavior:

Beeing in `/Users/USER/kyma/kyma` dir, it fails with:

`kyma provision gke -n $CLUSTER_NAME -l $GCP_ZONE -p $GCP_PROJECT -c ~/Downloads/my-sa.json
X Provisioning GKE cluster
Error: unable to provision gcp cluster: There are some problems with the configuration, described below.
The Terraform configuration must be valid before initialization so that
Terraform can determine which modules and providers need to be installed.
Error: Failed to read module directory
Module directory ../../.kyma/clusters/gcp/REDACTED_PROJECT/REDACTED_CLUSTER does
not exist or cannot be read.`

When cd into /Users/USER it started working…

**Comment by clebs** [comment]
I did some research and there is a complex combination of problems here:
1. Terraform init converts absolute paths of target directories to relative: https://github.com/hashicorp/terraform/blob/83630a7003fb8b868a3bf940798326634c3c6acc/command/meta_config.go#L29-L51
2. On my Macbook, if I cd into `/tmp` and then run `ls ../Users` the result is: `ls: ../Users: No such file or directory`
    If I run `ls ..` the list of directories does not contain `/Users`. So `/tmp` is probably a simlink of some sort and therefore relative paths to `/Users` do not work.

Given this setup, this bug can not be fixed since we can't change what terraform is doing with the path and the `/tmp` issue is inherent to the Operating System.

Regarding the case from @a-thaler, I just tested provisioning from this exact folder (`/Users/USER/kyma/kyma`) and it worked. Please check what might be different on your path; Maybe one of those folders is a symlink or something that would break a relative path.
