### ISSUE TITLE
Initialise and deploy Function via Kyma CLI

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/cli#551]
**Description**

Support two basic commands for serverless in kyma CLI:
 - kyma function init
 - kyma function apply

Would be great to have it realised via library (serverless domain) which kyma CLI would be calling to delegate serverless oriented tasks

**User Journey**

1. As a CLI user I want to generate a function [development workspace ](https://github.com/kyma-project/community/blob/master/collaboration/sig-core/proposals/extending-kyma-cli.md#local-workspace-setup)on my local machine.
This should generate src files for the function and a config.yaml for the function resources configuration on the target runtime.

    `kyma function init --runtime nodejs ...`

2. I develop the function src. I can run the code locally (i.e via express server). I can test it
3. I can configure a function trigger in the config.yaml
4. I can deploy the function by [applying local code and config to the remote cluster](https://github.com/kyma-project/community/blob/master/collaboration/sig-core/proposals/extending-kyma-cli.md#commands-that-use-config)

   `kyma function apply ... `
 

**Reasons**

Provide CLI tools around serverless for Business Application Developers

**Attachments**
![Screen Shot 2020-09-02 at 14 12 34](https://user-images.githubusercontent.com/6783567/91979666-64913700-ed26-11ea-9f0b-179ca52a21af.png)

**Comment by kwiatekus** [comment]
It should be possible to deploy function from:
 - **git repo**
- local sources

**Comment by kwiatekus** [comment]
`function init` is generating folder layout locally (appropraite to selected runtime)
`function create` will create Function CR (+ GitRepo CR, if function source was defined as git repo via cli command switch)

**Comment by pPrecel** [comment]
Me and @m00g3n prepared POC:

We implemented `function init` (with flags `--dir`, `--name`, `--namespace` and `--runtime`) and `function apply` (with flags `--dir` and `--dry-run`). Our solution is documented in [this PR](https://github.com/kyma-project/cli/pull/573).

My propositions of improves:
* Create a dedicated label for resources created by CLI. Because (for example) when we want to change the name of the function or other resource, CLI should remove from cluster resources with old names and CLI should find those resources using a special label.
* In my opinion whole changes proposed in PR should be located in a dedicated component or project. It's because of problems with different versions of dependencies used in the `cli` project and the `function-controller`.

**Comment by a-thaler** [comment]
To pro-actively start reviewing you can have a look here already:
https://github.com/kyma-project/cli/pull/581
https://github.com/m00g3n/hydroform/tree/add-serverless-function-api
https://github.com/pPrecel/hydroform/tree/extract-operator-manager-to-the-hydroform
