### ISSUE TITLE
New Installation: support K3s installation on Windows

### ISSUE THREAD

**Issue by tobiscr** [kyma-project/cli#695]
**Description**

Windows user have to be able to run Kyma with K3s on Windows. Evaluate the way how to use K3s (e.g. using Windows subsystem) to get K3s running and document the steps.

**Reasons**

Windows users have to be able to evaluate Kyma on Windows.

**Attachments**

-

**Comment by shorim** [comment]
It turned out that `k3d` is already supported natively on windows and no need to use windows subsystem for linux.
Users can easily install `k3d` on windows using `Chocolatey`: `choco install k3d` (https://chocolatey.org/packages/k3d/)

After installing `k3d`, users can provision a `k3s` cluster and deploy `Kyma` on it as shown in the screenshot:
![kyma_alpha](https://user-images.githubusercontent.com/25311301/109313309-59881100-7848-11eb-9924-daf18623c8a0.png)

**Comment by tobiscr** [comment]
@NHingerl : can you please follow up and extend the docs to cover the Windows installation for K3d.

**Comment by NHingerl** [comment]
> @NHingerl : can you please follow up and extend the docs to cover the Windows installation for K3d.

I plan to review https://github.com/kyma-project/kyma/pull/10697 when the installation procedure is finalized and update the docs accordingly. Please let me know if there's additional documentation needed.

**Comment by a-thaler** [comment]
So let's close the ticket. It is working on windows and docu is planned to be covered
