### ISSUE TITLE
Shell completion does not work for Zsh

### ISSUE THREAD

**Issue by clebs** [kyma-project/cli#90]
**Description**
Following the instructions provided by cobra to enable completion for the kyma CLI commands does not work showing the following error:
`/dev/fd/11:type:299: bad option: -t`

**Expected result**

Completions work after running the command as explained by the output of `kyma completion -h`

**Actual result**

Error is displayed:
`/dev/fd/11:type:299: bad option: -t`

**Steps to reproduce**
1. Install Kyma CLI as explained here: https://github.com/kyma-project/cli/releases/tag/v0.7.0
2. Run `. <(kyma completion)`, which should add the completions code to your bash session .

**Comment by suleymanakbas91** [comment]
Currently, Kyma CLI shell completion does not support Zsh. That's why you see this error. I created a [PR](#181) to add support but it is blocked by [this bug](https://github.com/spf13/cobra/issues/881) in cobra. As soon as the bug gets fixed (there is already an open [PR](https://github.com/spf13/cobra/pull/887)), I'll merge my PR to provide support for Zsh as well.

**Comment by suleymanakbas91** [comment]
The bug seems not to be fixed in the near future. We should hard-code the completion code for zsh just like some other clients (e.g. [minikube](https://github.com/kubernetes/minikube/blob/165c1afd331765aaa94d8db684b0045fb0713cc9/cmd/minikube/cmd/completion.go#L108)).
